<?php

class Model_AffiliateSetting extends \Model_Base
{
    protected static $_table_name = 'affiliate_settings';
    protected static $_parent_key = null;
    protected static $_primary_key = ['id'];

    protected static $_properties = [
        'id'                        => [
            'data_type' => 'bigint',
            'label'     => 'id',
            'form'      => ['type' => false],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'system_id'                  => [
            'data_type' => 'bigint',
            'label'     => 'id',
            'form'      => ['type' => false],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'affiliate_type'             => [
            'data_type' => 'enum',
            'label'     => 'affiliate_type',
            'options'    => ['deposit', 'withdrawal', 'bet', 'win', 'netwin','register'],
            'form'       => [
                'type'        => 'radio',
                'options'     => ['deposit' => 'deposit', 'withdrawal' => 'withdrawal', 'bet' => 'bet', 'win' => 'win', 'netwin' => 'netwin', 'register' => 'register'],
                'placeholder' => 'status',
                'class'       => 'form-radio',
            ],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'period_type'                 => [
            'data_type' => 'enum',
            'label'     => 'period_type',
            'validation' => [
                'required',
            ],
            'options'    => ['daily', 'weekly', 'monthly', 'yearly'],
            'form'       => [
                'type'        => 'radio',
                'options'     => ['daily' => 'daily', 'weekly' => 'weekly', 'monthly' => 'monthly', 'yearly' => 'yearly'],
                'placeholder' => 'status',
                'class'       => 'form-radio',
            ],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'carryover'        => [
            'data_type' => 'int',
            'label'      => 'carryover',
            'validation' => [
                'required',
            ],
            'table'      => true,
            'sort'       => true,
            'search'     => true,
            'align'      => 'left',
            'default'    => null,
        ],
        'base_rate'        => [
            'data_type' => 'decimal',
            'label'      => 'base_rate',
            'validation' => [
                'required',
            ],
            'form'       => [
                'type'        => 'text',
                'placeholder' => 'base_rate',
                'class'       => 'form-control',
            ],
            'table'      => true,
            'sort'       => true,
            'search'     => true,
            'align'      => 'right',
            'default'    => null,
        ],
        'min_limit'        => [
            'data_type' => 'decimal',
            'label'      => 'min_limit',
            'validation' => [
                'required',
            ],
            'form'       => [
                'type'        => 'text',
                'placeholder' => 'base_rate',
                'class'       => 'form-control',
            ],
            'table'      => true,
            'sort'       => true,
            'search'     => true,
            'align'      => 'right',
            'default'    => null,
        ],
        'max_limit'        => [
            'data_type' => 'decimal',
            'label'      => 'min_limit',
            'validation' => [
                'required',
            ],
            'form'       => [
                'type'        => 'text',
                'placeholder' => 'base_rate',
                'class'       => 'form-control',
            ],
            'table'      => true,
            'sort'       => true,
            'search'     => true,
            'align'      => 'right',
            'default'    => null,
        ],
        'closing_date'     => [
            'data_type' => 'int',
            'label'     => 'closing_date',
            'validation' => [
                'required',
            ],
            'form'      => ['type' => false],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'pay_date'                  => [
            'data_type' => 'int',
            'label'     => 'pay_date',
            'validation' => [
                'required',
            ],
            'form'      => ['type' => false],
            'table'     => true,
            'sort'      => true,
            'search'    => true,
            'align'     => 'left',
            'default'   => null,
        ],
        'status'                    => [
            'data_type'  => 'enum',
            'label'      => 'status',
            'validation' => [
                'required',
            ],
            'options'    => ['active', 'inactive'],
            'form'       => [
                'type'        => 'radio',
                'options'     => ['active' => 'active', 'inactive' => 'inactive'],
                'placeholder' => 'status',
                'class'       => 'form-radio',
            ],
            'table'      => true,
            'sort'       => true,
            'search'     => false,
            'align'      => 'center',
            'default'    => 'active',
        ],
        'created_id'                => [
            'data_type' => 'int',
            'label'     => 'created_id',
            'form'      => ['type' => false],
            'table'     => false,
            'sort'      => false,
            'search'    => false,
            'align'     => 'center',
            'default'   => null,
        ],
        'created_at'                => [
            'data_type' => 'int',
            'label'     => 'created_at',
            'form'      => ['type' => false],
            'sort'      => true,
            'search'    => false,
            'default'   => null,
        ],
        'updated_id'                => [
            'data_type' => 'int',
            'label'     => 'updated_id',
            'form'      => ['type' => false],
            'table'     => false,
            'sort'      => false,
            'search'    => false,
            'align'     => 'center',
            'default'   => null,
        ],
        'updated_at'                => [
            'data_type' => 'int',
            'label'     => 'updated_at',
            'form'      => ['type' => false],
            'table'     => false,
            'sort'      => false,
            'search'    => false,
            'align'     => 'center',
            'default'   => null,
        ],
        'deleted_id'                => [
            'data_type' => 'int',
            'label'     => 'deleted_id',
            'form'      => ['type' => false],
            'table'     => false,
            'sort'      => false,
            'search'    => false,
            'align'     => 'center',
            'default'   => null,
        ],
        'deleted_at'                => [
            'data_type' => 'int',
            'label'     => 'deleted_at',
            'form'      => ['type' => false],
            'table'     => false,
            'sort'      => false,
            'search'    => false,
            'align'     => 'center',
            'default'   => null,
        ],
    ];

}